author = 'Abhinav Mishra'
baseURL = 'https://abhi.dev'
languageCode = 'en-us'
title = 'My Blog'
theme = "cupper-hugo-theme"
disqusShortname = ""
googleAnalytics = ""

[menus]
[[menus.nav]]
  name = "Home"
  url = "/"
  
[[menus.nav]]
  name = "Blogs"
  url = "/blogs"

[params]
moveFooterToHeader = true
logoAlt = "avatar"
customCss = ["/css/overrides.css"]
customJs = ["https://kit.fontawesome.com/14923bcc9a.js"]

[[params.social]]
  url = "https://github.com/abhinavmsra"
  fa_icon = "fab fa-github fa-lg"

[[params.social]]
  url = "https://twitter.com/abhinavmsra"
  fa_icon = "fab fa-twitter fa-lg"